---
name: Reviewdog
on: [pull_request]
jobs:
  hadolint:
    name: Linter / hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review # Default is github-pr-check
          fail_on_error: true
          tool_name: hadolint
          # hadolint_ignore: DL3008
          hadolint_flags: --config .hadolint.yaml
  markdownlint:
    name: Linter / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          reviewdog_flags: -name markdownlint
          markdownlint_flags: --config .markdownlint.yaml .
  actionlint:
    name: Linter / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
